// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9KwtGWzVzVNgDW6U-_Lqd77pTzfj1lyA',
    appId: '1:273624108127:web:8a63c06a120684c0941fea',
    messagingSenderId: '273624108127',
    projectId: 'nabeel-khanjee',
    authDomain: 'nabeel-khanjee.firebaseapp.com',
    storageBucket: 'nabeel-khanjee.appspot.com',
    measurementId: 'G-WVXFV40PRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeomWz6FpM_AkJrB8inUJp399rouIDYIo',
    appId: '1:273624108127:android:17a4af3c8c43f5d9941fea',
    messagingSenderId: '273624108127',
    projectId: 'nabeel-khanjee',
    storageBucket: 'nabeel-khanjee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5JxWKjPVgy88Ap2_aItd4bRXbk-dIYPI',
    appId: '1:273624108127:ios:dffc8975db9ff06e941fea',
    messagingSenderId: '273624108127',
    projectId: 'nabeel-khanjee',
    storageBucket: 'nabeel-khanjee.appspot.com',
    iosClientId: '273624108127-6mqb4e7lqt6lm5r37oshhvvvhsu8rooh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5JxWKjPVgy88Ap2_aItd4bRXbk-dIYPI',
    appId: '1:273624108127:ios:dffc8975db9ff06e941fea',
    messagingSenderId: '273624108127',
    projectId: 'nabeel-khanjee',
    storageBucket: 'nabeel-khanjee.appspot.com',
    iosClientId: '273624108127-6mqb4e7lqt6lm5r37oshhvvvhsu8rooh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfile',
  );
}
